# 1 - Numpy introduction

Import the numpy package under the name np


In [3]:
import numpy as np

Print the numpy version

In [4]:
print(np)

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>


# 2 - Definition, creation & atributes

* Define a 3 lenght numpy array
* Define a 2D numpy array
* Create a null vector of size 10 
* Create a vector with values ranging from 10 to 49 



In [5]:
myarray = np.array([1,2,3])
myarray = np.array([[2,3],[5,6]])
x=np.zeros(10)
y=np.arange(10,50)

Calculate the array dimensions of the array, the number of elements and the total bytes consumed

In [6]:
myarray = np.array([[[1,2,3],[1,2,3],[1,2,3]],
                    [[1,2,3],[1,2,3],[1,2,3]]])

print("Size of the array: ", myarray.itemsize)
print("Number of elements: ", myarray.size)
print("Total bytes consumed: ", myarray.nbytes)


Size of the array:  8
Number of elements:  18
Total bytes consumed:  144


# 3 - Indexing - Access

Create a null vector of size 10 but the fifth value which is 1

In [7]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Reverse a vector (first element becomes last)


In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Create a 2d array (shape =(10,10)) with 1 on the border and 0 inside




In [9]:
import numpy as np
myarray = np.ones((10,10))

myarray[1:-1,1:-1] = 0
print(myarray)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 4 - Basic methods


Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
import numpy as np
indices = np.array([1,2,0,0,4,0])
np.nonzero(indices)

(array([0, 1, 4]),)

Using myarray calculate:
- minimum
- maximum of each row
- mean of each column
- sum
- sort myarray
- cast to float
- calculate if any value is > 90

In [11]:
myarray = np.array([[10, 29, 38, 89, 87],
                    [71, 66, 32, 21, 83],
                    [30, 54,  5, 11, 54],
                    [51, 12, 53, 43, 24],
                    [97, 47, 34, 91, 69]])
print(myarray.min())
 
rowmax=np.amax(myarray, axis=1)
print(rowmax)
 
colmean = np.mean(myarray, axis=0)
print(colmean)
 
npsum = np.sum(myarray)
print(npsum)
 
npsort = np.sort(myarray)
print(npsort)
 
myarray.astype(float)
 
x=np.where(myarray>90)
print("Values are bigger than 90: ", x)


5
[89 83 54 53 97]
[51.8 41.6 32.4 51.  63.4]
1201
[[10 29 38 87 89]
 [21 32 66 71 83]
 [ 5 11 30 54 54]
 [12 24 43 51 53]
 [34 47 69 91 97]]
Values are bigger than 90:  (array([4, 4]), array([0, 3]))


# 5 - Mathematical Operators

Using myarray calculate:
- tangent rounded to the 2 decimal
- logaritmic of each row rounded to the 3 decimal
- hyperbolic sine of each column rounded to the 4 decimal
- multiply by pi

In [12]:
myarray = np.array([[0.1 , 0.29, 0.38, 0.87, 0.89],
                    [0.21, 0.32, 0.66, 0.71, 0.83],
                    [0.05, 0.11, 0.3 , 0.54, 0.54],
                    [0.12, 0.24, 0.43, 0.51, 0.53],
                    [0.34, 0.47, 0.69, 0.91, 0.97]])
print(myarray)

new = np.tan(myarray)
print(new)
new = [np.round(elem,2) for elem in new]
print(new)

logaritmic = np.log(myarray)
logaritmic = [np.round(elem,3) for elem in logaritmic]
print(logaritmic)

hyperbolicSine = np.sinh(myarray)
hyperbolicSine = [np.round(elem,4) for elem in hyperbolicSine]
print(hyperbolicSine)

multiplyPi = np.pi * myarray
print(multiplyPi)

[[0.1  0.29 0.38 0.87 0.89]
 [0.21 0.32 0.66 0.71 0.83]
 [0.05 0.11 0.3  0.54 0.54]
 [0.12 0.24 0.43 0.51 0.53]
 [0.34 0.47 0.69 0.91 0.97]]
[[0.10033467 0.29841279 0.39941272 1.18532486 1.23459946]
 [0.21314244 0.33138941 0.77610491 0.85952867 1.09343292]
 [0.05004171 0.11044582 0.30933625 0.59942962 0.59942962]
 [0.12057934 0.2447167  0.45862102 0.55935872 0.58591701]
 [0.35373688 0.5079659  0.82533611 1.28636938 1.45920113]]
[array([0.1 , 0.3 , 0.4 , 1.19, 1.23]), array([0.21, 0.33, 0.78, 0.86, 1.09]), array([0.05, 0.11, 0.31, 0.6 , 0.6 ]), array([0.12, 0.24, 0.46, 0.56, 0.59]), array([0.35, 0.51, 0.83, 1.29, 1.46])]
[array([-2.303, -1.238, -0.968, -0.139, -0.117]), array([-1.561, -1.139, -0.416, -0.342, -0.186]), array([-2.996, -2.207, -1.204, -0.616, -0.616]), array([-2.12 , -1.427, -0.844, -0.673, -0.635]), array([-1.079, -0.755, -0.371, -0.094, -0.03 ])]
[array([0.1002, 0.2941, 0.3892, 0.984 , 1.0122]), array([0.2115, 0.3255, 0.709 , 0.7712, 0.9286]), array([0.05  , 0.1102, 0.30

Using myarray calculate:
* define a function that squares the components and makes the sum of all of them
* apply the function through axis 0
* apply the function through axis 1
* apply the function through both axis

In [13]:
myarray = np.array([[0.1 , 0.29, 0.38, 0.87, 0.89],
                    [0.21, 0.32, 0.66, 0.71, 0.83],
                    [0.05, 0.11, 0.3 , 0.54, 0.54],
                    [0.12, 0.24, 0.43, 0.51, 0.53],
                    [0.34, 0.47, 0.69, 0.91, 0.97]])
print(myarray)


square = np.square([myarray])
sumSquare = np.sum([square])
print(sumSquare)

print(np.apply_along_axis(sorted, 0, myarray))
print(np.apply_along_axis(sorted, 1, myarray))
print(np.apply_along_axis(sorted, 0-1, myarray))

[[0.1  0.29 0.38 0.87 0.89]
 [0.21 0.32 0.66 0.71 0.83]
 [0.05 0.11 0.3  0.54 0.54]
 [0.12 0.24 0.43 0.51 0.53]
 [0.34 0.47 0.69 0.91 0.97]]
7.6299
[[0.05 0.11 0.3  0.51 0.53]
 [0.1  0.24 0.38 0.54 0.54]
 [0.12 0.29 0.43 0.71 0.83]
 [0.21 0.32 0.66 0.87 0.89]
 [0.34 0.47 0.69 0.91 0.97]]
[[0.1  0.29 0.38 0.87 0.89]
 [0.21 0.32 0.66 0.71 0.83]
 [0.05 0.11 0.3  0.54 0.54]
 [0.12 0.24 0.43 0.51 0.53]
 [0.34 0.47 0.69 0.91 0.97]]
[[0.1  0.29 0.38 0.87 0.89]
 [0.21 0.32 0.66 0.71 0.83]
 [0.05 0.11 0.3  0.54 0.54]
 [0.12 0.24 0.43 0.51 0.53]
 [0.34 0.47 0.69 0.91 0.97]]


What is the result of the following expression?
```python
0 * np.nan
np.nan==np.nan
np.inf > np.nan
np.nan - np.nan
```

In [14]:
print(0 * np.nan)
print(np.nan==np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
"""
nan
False
False
nan
"""

nan
False
False
nan


'\nnan\nFalse\nFalse\nnan\n'

# 6 - Random Family


Using np.random:
- generate float random numbers between 0-1 in shape (1,4,5)
- generate integer numbers between 0-1000 in shape (4,4)
- generate float random numbers with normal distribution in shape (3,3,2)
- generate 20 random integers between [0,1,2] with double probabilities of value 0

In [16]:
import numpy as np

rng = np.random.default_rng()
rng.random((1, 4, 5))

rng.integers(0, 1000)

np.random.normal(3, 3, 2) 



array([5.19273925, 4.04515778])

# 7 - Shape transformations

using myarray:
* reshape to (2,12)
* reshape to (6,4)
* add new last axis
* add new medium axis
* add new first axis
* split by 3 column (result = (3,3) and (3,5))
* collapse to 1D array


In [ ]:
import numpy as np
myarray = np.arange(24).reshape((3,8))
print(myarray)
myarray = np.arange(24).reshape((6,4))
print(myarray)
myarray[np.newaxis, :]

myarray[:, np.newaxis]
np.split((3,3), (3,5))

myarray.flatten



[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


<function ndarray.flatten>

# 8 - Combinations of arrays


using arr1,arr2:
* repeat 3 times arr1 using repeat
* repeat 5 times arr2 using tile
* concatenate both along axis 0
* concatenate both along axis 1
* stack both vertically
* stack both horizontally

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(np.repeat(arr1, 3, axis= 0))
print(np.tile(arr2, (5, 1)))
print(np.concatenate((arr1,arr2), axis =0))
print(np.concatenate((arr1,arr2), axis =1))
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1, arr2)))



[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [ 7  8  9]
 [10 11 12]
 [ 7  8  9]
 [10 11 12]
 [ 7  8  9]
 [10 11 12]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# 9 - Linear Algebra


* generate a random integer array (between 1-100) with shape (3,3)
* calculate elemnt by element product
* calculate matrix product
* calculate the norm
* calculate the determinant
* calculate the rank
* calculate the inverse

In [ ]:
random = np.random.randint(1, high=100, size=(3,3), dtype=int)
print(np.prod(random, axis=None))
print(np.matmul(random,random))
print(np.linalg.norm(random))
print(np.linalg.det(random))
print(np.linalg.matrix_rank(random))
print(np.linalg.inv(random))

31374230580000
[[7651 8550 2760]
 [4082 5431 1620]
 [3164 3948 2065]]
134.1379886534758
-75355.00000000006
3
[[-0.00510915  0.03344171 -0.01214253]
 [ 0.01764979 -0.02461681  0.00298587]
 [-0.01913609  0.01616349  0.0298454 ]]


Solve the linear problem between A and b

In [ ]:
A = np.array([[1,2,3],[14,2,52],[-2,5,20]])
b = np.array([0.5,0,13])
print(np.linalg.solve(A, b))

[-1.51958225  0.42036554  0.39295039]


# 10 - Save / Load methods

What is the result of the following expression?
```python
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

np.save('arr1.npy',arr1)
np.save('arr2.npy',arr2)
print(np.load('arr1.npy'))
print(np.load('arr2.npy'))
np.savez('arr1_arr2.npz',arr1=arr1,arr2=arr2)
arr3 = np.load('arr1_arr2.npz')
print(arr3['arr1'])
print(arr3['arr2'])
```

In [ ]:
"""
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
"""

'\n[[1 2 3]\n [4 5 6]]\n[[ 7  8  9]\n [10 11 12]]\n[[1 2 3]\n [4 5 6]]\n[[ 7  8  9]\n [10 11 12]]\n'